language: node_js
sudo: false
node_js:
    - '4.1.0'
before_install: npm install -g gulp-cli
install: npm install
services:
    - mongodb
after_script: npm install coveralls && cat ./coverage/lcov.info | coveralls
